// Generated by Ignite ignite.com/cli
//ignite/pkg/cosmosgen/templates/module/types.ts.tpl

{{ range .Module.Types }}import { {{ .Name }} } from "{{ resolveFile .FilePath }}"
{{ end }}

export {     
    {{ range .Module.Types }}{{ .Name }},
    {{ end }}
 }
